services:
  db:
    image: postgis/postgis:15-3.4-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: saleshub_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - saleshub_net
    healthcheck:
      # Тут теж підставляємо змінні
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend-core/Project/Project
    ports:
      - "8080:8080"
    environment:
    
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - AWS_S3_BUCKET_NAME=${AWS_S3_BUCKET_NAME}
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - Jwt__Key=${JWT_SECRET_KEY}
      # Оновлюємо рядок підключення для C#, щоб він теж брав паролі зі змінних!
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
    networks:
      - saleshub_net
    depends_on:
      db:
        condition: service_healthy
  frontend:
    build:
      context: ./frontend-core
    ports:
      - "5173:5173"
    volumes:
      - ./frontend-core:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_GOOGLE_MAPS_API_KEY=${VITE_GOOGLE_MAPS_API_KEY}
    networks:
      - saleshub_net
    depends_on:
      - backend

volumes:
  pgdata:

networks:
  saleshub_net:
    driver: bridge
