--
-- PostgreSQL database dump
--



-- Dumped from database version 18.3
-- Dumped by pg_dump version 18.3

-- Started on 2026-05-26 12:34:01

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 2 (class 3079 OID 31989)
-- Name: postgis; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS postgis WITH SCHEMA public;


--
-- TOC entry 6108 (class 0 OID 0)
-- Dependencies: 2
-- Name: EXTENSION postgis; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION postgis IS 'PostGIS geometry and geography spatial types and functions';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 235 (class 1259 OID 33135)
-- Name: AspNetRoleClaims; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetRoleClaims" (
    "Id" integer NOT NULL,
    "RoleId" integer NOT NULL,
    "ClaimType" text,
    "ClaimValue" text
);


ALTER TABLE public."AspNetRoleClaims" OWNER TO postgres;

--
-- TOC entry 234 (class 1259 OID 33134)
-- Name: AspNetRoleClaims_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."AspNetRoleClaims" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AspNetRoleClaims_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 227 (class 1259 OID 33079)
-- Name: AspNetRoles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetRoles" (
    "Id" integer NOT NULL,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text
);


ALTER TABLE public."AspNetRoles" OWNER TO postgres;

--
-- TOC entry 226 (class 1259 OID 33078)
-- Name: AspNetRoles_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."AspNetRoles" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AspNetRoles_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 237 (class 1259 OID 33150)
-- Name: AspNetUserClaims; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetUserClaims" (
    "Id" integer NOT NULL,
    "UserId" integer NOT NULL,
    "ClaimType" text,
    "ClaimValue" text
);


ALTER TABLE public."AspNetUserClaims" OWNER TO postgres;

--
-- TOC entry 236 (class 1259 OID 33149)
-- Name: AspNetUserClaims_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."AspNetUserClaims" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AspNetUserClaims_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 238 (class 1259 OID 33164)
-- Name: AspNetUserLogins; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetUserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text,
    "UserId" integer NOT NULL
);


ALTER TABLE public."AspNetUserLogins" OWNER TO postgres;

--
-- TOC entry 239 (class 1259 OID 33179)
-- Name: AspNetUserRoles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetUserRoles" (
    "UserId" integer NOT NULL,
    "RoleId" integer NOT NULL
);


ALTER TABLE public."AspNetUserRoles" OWNER TO postgres;

--
-- TOC entry 240 (class 1259 OID 33196)
-- Name: AspNetUserTokens; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetUserTokens" (
    "UserId" integer NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text
);


ALTER TABLE public."AspNetUserTokens" OWNER TO postgres;

--
-- TOC entry 229 (class 1259 OID 33088)
-- Name: AspNetUsers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetUsers" (
    "Id" integer NOT NULL,
    "Name" text NOT NULL,
    "Surname" text NOT NULL,
    "Category" integer NOT NULL,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL
);


ALTER TABLE public."AspNetUsers" OWNER TO postgres;

--
-- TOC entry 228 (class 1259 OID 33087)
-- Name: AspNetUsers_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."AspNetUsers" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AspNetUsers_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 231 (class 1259 OID 33105)
-- Name: Locations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Locations" (
    "Id" integer NOT NULL,
    "Name" text NOT NULL,
    "Address" text NOT NULL,
    "City" text NOT NULL,
    "Coordinates" public.geometry NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL
);


ALTER TABLE public."Locations" OWNER TO postgres;

--
-- TOC entry 230 (class 1259 OID 33104)
-- Name: Locations_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Locations" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Locations_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 233 (class 1259 OID 33119)
-- Name: OfferCategories; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."OfferCategories" (
    "Id" integer NOT NULL,
    "Name" text NOT NULL,
    "IconUrl" text,
    "MarkerColor" text,
    "ParentId" integer,
    "CreatedAt" timestamp with time zone NOT NULL
);


ALTER TABLE public."OfferCategories" OWNER TO postgres;

--
-- TOC entry 232 (class 1259 OID 33118)
-- Name: OfferCategories_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."OfferCategories" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."OfferCategories_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 250 (class 1259 OID 33302)
-- Name: OfferImages; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."OfferImages" (
    "Id" integer NOT NULL,
    "ImageUrl" text NOT NULL,
    "IsMain" boolean NOT NULL,
    "OfferId" integer NOT NULL
);


ALTER TABLE public."OfferImages" OWNER TO postgres;

--
-- TOC entry 249 (class 1259 OID 33301)
-- Name: OfferImages_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."OfferImages" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."OfferImages_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 252 (class 1259 OID 33319)
-- Name: OfferReviews; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."OfferReviews" (
    "Id" integer NOT NULL,
    "OfferId" integer NOT NULL,
    "CreatedById" integer NOT NULL,
    "IsRecommended" boolean NOT NULL,
    "Comment" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL
);


ALTER TABLE public."OfferReviews" OWNER TO postgres;

--
-- TOC entry 251 (class 1259 OID 33318)
-- Name: OfferReviews_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."OfferReviews" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."OfferReviews_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 244 (class 1259 OID 33232)
-- Name: Offers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Offers" (
    "Id" integer NOT NULL,
    "Title" text NOT NULL,
    "Description" text NOT NULL,
    "IsActive" boolean NOT NULL,
    "NewPrice" numeric NOT NULL,
    "OldPrice" numeric,
    "ValidFrom" timestamp with time zone,
    "ValidTo" timestamp with time zone,
    "Creator" integer NOT NULL,
    "CategoryId" integer NOT NULL,
    "PlaceId" integer NOT NULL,
    "CreatedById" integer,
    "CreatedAt" timestamp with time zone NOT NULL
);


ALTER TABLE public."Offers" OWNER TO postgres;

--
-- TOC entry 243 (class 1259 OID 33231)
-- Name: Offers_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Offers" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Offers_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 246 (class 1259 OID 33264)
-- Name: PlaceImages; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."PlaceImages" (
    "Id" integer NOT NULL,
    "ImageUrl" text NOT NULL,
    "IsMain" boolean NOT NULL,
    "PlaceId" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL
);


ALTER TABLE public."PlaceImages" OWNER TO postgres;

--
-- TOC entry 245 (class 1259 OID 33263)
-- Name: PlaceImages_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."PlaceImages" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."PlaceImages_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 248 (class 1259 OID 33282)
-- Name: PlaceLocations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."PlaceLocations" (
    "Id" integer NOT NULL,
    "PlaceId" integer NOT NULL,
    "LocationId" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL
);


ALTER TABLE public."PlaceLocations" OWNER TO postgres;

--
-- TOC entry 247 (class 1259 OID 33281)
-- Name: PlaceLocations_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."PlaceLocations" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."PlaceLocations_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 242 (class 1259 OID 33212)
-- Name: Places; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Places" (
    "Id" integer NOT NULL,
    "Name" text NOT NULL,
    "Description" text NOT NULL,
    "IsOnline" boolean NOT NULL,
    "OfferUrl" text NOT NULL,
    "CreatedById" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL
);


ALTER TABLE public."Places" OWNER TO postgres;

--
-- TOC entry 241 (class 1259 OID 33211)
-- Name: Places_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Places" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Places_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 254 (class 1259 OID 33343)
-- Name: UserSavedOffers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."UserSavedOffers" (
    "Id" integer NOT NULL,
    "OfferId" integer NOT NULL,
    "UserId" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL
);


ALTER TABLE public."UserSavedOffers" OWNER TO postgres;

--
-- TOC entry 253 (class 1259 OID 33342)
-- Name: UserSavedOffers_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."UserSavedOffers" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."UserSavedOffers_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 225 (class 1259 OID 33071)
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- TOC entry 6083 (class 0 OID 33135)
-- Dependencies: 235
-- Data for Name: AspNetRoleClaims; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."AspNetRoleClaims" ("Id", "RoleId", "ClaimType", "ClaimValue") FROM stdin;
\.


--
-- TOC entry 6075 (class 0 OID 33079)
-- Dependencies: 227
-- Data for Name: AspNetRoles; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."AspNetRoles" ("Id", "Name", "NormalizedName", "ConcurrencyStamp") FROM stdin;
1	Admin	ADMIN	\N
2	User	USER	\N
\.


--
-- TOC entry 6085 (class 0 OID 33150)
-- Dependencies: 237
-- Data for Name: AspNetUserClaims; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."AspNetUserClaims" ("Id", "UserId", "ClaimType", "ClaimValue") FROM stdin;
\.


--
-- TOC entry 6086 (class 0 OID 33164)
-- Dependencies: 238
-- Data for Name: AspNetUserLogins; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."AspNetUserLogins" ("LoginProvider", "ProviderKey", "ProviderDisplayName", "UserId") FROM stdin;
\.


--
-- TOC entry 6087 (class 0 OID 33179)
-- Dependencies: 239
-- Data for Name: AspNetUserRoles; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."AspNetUserRoles" ("UserId", "RoleId") FROM stdin;
\.


--
-- TOC entry 6088 (class 0 OID 33196)
-- Dependencies: 240
-- Data for Name: AspNetUserTokens; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."AspNetUserTokens" ("UserId", "LoginProvider", "Name", "Value") FROM stdin;
\.


--
-- TOC entry 6077 (class 0 OID 33088)
-- Dependencies: 229
-- Data for Name: AspNetUsers; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."AspNetUsers" ("Id", "Name", "Surname", "Category", "UserName", "NormalizedUserName", "Email", "NormalizedEmail", "EmailConfirmed", "PasswordHash", "SecurityStamp", "ConcurrencyStamp", "PhoneNumber", "PhoneNumberConfirmed", "TwoFactorEnabled", "LockoutEnd", "LockoutEnabled", "AccessFailedCount") FROM stdin;
\.


--
-- TOC entry 6079 (class 0 OID 33105)
-- Dependencies: 231
-- Data for Name: Locations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Locations" ("Id", "Name", "Address", "City", "Coordinates", "CreatedAt") FROM stdin;
\.


--
-- TOC entry 6081 (class 0 OID 33119)
-- Dependencies: 233
-- Data for Name: OfferCategories; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."OfferCategories" ("Id", "Name", "IconUrl", "MarkerColor", "ParentId", "CreatedAt") FROM stdin;
1	Розваги	\N	#a83058ff	\N	2026-05-09 03:00:00+03
2	Заклади	\N	#fdad35ff	\N	2026-05-09 03:00:00+03
3	Культура	\N	#115e10ff	\N	2026-05-09 03:00:00+03
4	Книги	\N	#5c2917ff	\N	2026-05-09 03:00:00+03
5	Спорт	\N	#1f1342ff	\N	2026-05-09 03:00:00+03
\.


--
-- TOC entry 6098 (class 0 OID 33302)
-- Dependencies: 250
-- Data for Name: OfferImages; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."OfferImages" ("Id", "ImageUrl", "IsMain", "OfferId") FROM stdin;
\.


--
-- TOC entry 6100 (class 0 OID 33319)
-- Dependencies: 252
-- Data for Name: OfferReviews; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."OfferReviews" ("Id", "OfferId", "CreatedById", "IsRecommended", "Comment", "CreatedAt") FROM stdin;
\.


--
-- TOC entry 6092 (class 0 OID 33232)
-- Dependencies: 244
-- Data for Name: Offers; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Offers" ("Id", "Title", "Description", "IsActive", "NewPrice", "OldPrice", "ValidFrom", "ValidTo", "Creator", "CategoryId", "PlaceId", "CreatedById", "CreatedAt") FROM stdin;
\.


--
-- TOC entry 6094 (class 0 OID 33264)
-- Dependencies: 246
-- Data for Name: PlaceImages; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."PlaceImages" ("Id", "ImageUrl", "IsMain", "PlaceId", "CreatedAt") FROM stdin;
\.


--
-- TOC entry 6096 (class 0 OID 33282)
-- Dependencies: 248
-- Data for Name: PlaceLocations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."PlaceLocations" ("Id", "PlaceId", "LocationId", "CreatedAt") FROM stdin;
\.


--
-- TOC entry 6090 (class 0 OID 33212)
-- Dependencies: 242
-- Data for Name: Places; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Places" ("Id", "Name", "Description", "IsOnline", "OfferUrl", "CreatedById", "CreatedAt") FROM stdin;
\.


--
-- TOC entry 6102 (class 0 OID 33343)
-- Dependencies: 254
-- Data for Name: UserSavedOffers; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."UserSavedOffers" ("Id", "OfferId", "UserId", "CreatedAt") FROM stdin;
\.


--
-- TOC entry 6073 (class 0 OID 33071)
-- Dependencies: 225
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20260526092750_initial	9.0.14
\.


--
-- TOC entry 5844 (class 0 OID 32308)
-- Dependencies: 221
-- Data for Name: spatial_ref_sys; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.spatial_ref_sys (srid, auth_name, auth_srid, srtext, proj4text) FROM stdin;
\.


--
-- TOC entry 6109 (class 0 OID 0)
-- Dependencies: 234
-- Name: AspNetRoleClaims_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."AspNetRoleClaims_Id_seq"', 1, false);


--
-- TOC entry 6110 (class 0 OID 0)
-- Dependencies: 226
-- Name: AspNetRoles_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."AspNetRoles_Id_seq"', 2, true);


--
-- TOC entry 6111 (class 0 OID 0)
-- Dependencies: 236
-- Name: AspNetUserClaims_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."AspNetUserClaims_Id_seq"', 1, false);


--
-- TOC entry 6112 (class 0 OID 0)
-- Dependencies: 228
-- Name: AspNetUsers_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."AspNetUsers_Id_seq"', 1, false);


--
-- TOC entry 6113 (class 0 OID 0)
-- Dependencies: 230
-- Name: Locations_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Locations_Id_seq"', 1, false);


--
-- TOC entry 6114 (class 0 OID 0)
-- Dependencies: 232
-- Name: OfferCategories_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."OfferCategories_Id_seq"', 6, false);


--
-- TOC entry 6115 (class 0 OID 0)
-- Dependencies: 249
-- Name: OfferImages_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."OfferImages_Id_seq"', 1, false);


--
-- TOC entry 6116 (class 0 OID 0)
-- Dependencies: 251
-- Name: OfferReviews_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."OfferReviews_Id_seq"', 1, false);


--
-- TOC entry 6117 (class 0 OID 0)
-- Dependencies: 243
-- Name: Offers_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Offers_Id_seq"', 1, false);


--
-- TOC entry 6118 (class 0 OID 0)
-- Dependencies: 245
-- Name: PlaceImages_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."PlaceImages_Id_seq"', 1, false);


--
-- TOC entry 6119 (class 0 OID 0)
-- Dependencies: 247
-- Name: PlaceLocations_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."PlaceLocations_Id_seq"', 1, false);


--
-- TOC entry 6120 (class 0 OID 0)
-- Dependencies: 241
-- Name: Places_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Places_Id_seq"', 1, false);


--
-- TOC entry 6121 (class 0 OID 0)
-- Dependencies: 253
-- Name: UserSavedOffers_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."UserSavedOffers_Id_seq"', 1, false);


--
-- TOC entry 5864 (class 2606 OID 33143)
-- Name: AspNetRoleClaims PK_AspNetRoleClaims; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetRoleClaims"
    ADD CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id");


--
-- TOC entry 5851 (class 2606 OID 33086)
-- Name: AspNetRoles PK_AspNetRoles; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetRoles"
    ADD CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id");


--
-- TOC entry 5867 (class 2606 OID 33158)
-- Name: AspNetUserClaims PK_AspNetUserClaims; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserClaims"
    ADD CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id");


--
-- TOC entry 5870 (class 2606 OID 33173)
-- Name: AspNetUserLogins PK_AspNetUserLogins; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserLogins"
    ADD CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey");


--
-- TOC entry 5873 (class 2606 OID 33185)
-- Name: AspNetUserRoles PK_AspNetUserRoles; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserRoles"
    ADD CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId");


--
-- TOC entry 5875 (class 2606 OID 33205)
-- Name: AspNetUserTokens PK_AspNetUserTokens; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserTokens"
    ADD CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name");


--
-- TOC entry 5855 (class 2606 OID 33103)
-- Name: AspNetUsers PK_AspNetUsers; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUsers"
    ADD CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id");


--
-- TOC entry 5858 (class 2606 OID 33117)
-- Name: Locations PK_Locations; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Locations"
    ADD CONSTRAINT "PK_Locations" PRIMARY KEY ("Id");


--
-- TOC entry 5861 (class 2606 OID 33128)
-- Name: OfferCategories PK_OfferCategories; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."OfferCategories"
    ADD CONSTRAINT "PK_OfferCategories" PRIMARY KEY ("Id");


--
-- TOC entry 5893 (class 2606 OID 33312)
-- Name: OfferImages PK_OfferImages; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."OfferImages"
    ADD CONSTRAINT "PK_OfferImages" PRIMARY KEY ("Id");


--
-- TOC entry 5897 (class 2606 OID 33331)
-- Name: OfferReviews PK_OfferReviews; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."OfferReviews"
    ADD CONSTRAINT "PK_OfferReviews" PRIMARY KEY ("Id");


--
-- TOC entry 5883 (class 2606 OID 33247)
-- Name: Offers PK_Offers; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Offers"
    ADD CONSTRAINT "PK_Offers" PRIMARY KEY ("Id");


--
-- TOC entry 5886 (class 2606 OID 33275)
-- Name: PlaceImages PK_PlaceImages; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PlaceImages"
    ADD CONSTRAINT "PK_PlaceImages" PRIMARY KEY ("Id");


--
-- TOC entry 5890 (class 2606 OID 33290)
-- Name: PlaceLocations PK_PlaceLocations; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PlaceLocations"
    ADD CONSTRAINT "PK_PlaceLocations" PRIMARY KEY ("Id");


--
-- TOC entry 5878 (class 2606 OID 33225)
-- Name: Places PK_Places; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Places"
    ADD CONSTRAINT "PK_Places" PRIMARY KEY ("Id");


--
-- TOC entry 5901 (class 2606 OID 33351)
-- Name: UserSavedOffers PK_UserSavedOffers; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."UserSavedOffers"
    ADD CONSTRAINT "PK_UserSavedOffers" PRIMARY KEY ("Id");


--
-- TOC entry 5849 (class 2606 OID 33077)
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- TOC entry 5853 (class 1259 OID 33367)
-- Name: EmailIndex; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "EmailIndex" ON public."AspNetUsers" USING btree ("NormalizedEmail");


--
-- TOC entry 5862 (class 1259 OID 33362)
-- Name: IX_AspNetRoleClaims_RoleId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON public."AspNetRoleClaims" USING btree ("RoleId");


--
-- TOC entry 5865 (class 1259 OID 33364)
-- Name: IX_AspNetUserClaims_UserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_AspNetUserClaims_UserId" ON public."AspNetUserClaims" USING btree ("UserId");


--
-- TOC entry 5868 (class 1259 OID 33365)
-- Name: IX_AspNetUserLogins_UserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_AspNetUserLogins_UserId" ON public."AspNetUserLogins" USING btree ("UserId");


--
-- TOC entry 5871 (class 1259 OID 33366)
-- Name: IX_AspNetUserRoles_RoleId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_AspNetUserRoles_RoleId" ON public."AspNetUserRoles" USING btree ("RoleId");


--
-- TOC entry 5859 (class 1259 OID 33369)
-- Name: IX_OfferCategories_ParentId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_OfferCategories_ParentId" ON public."OfferCategories" USING btree ("ParentId");


--
-- TOC entry 5891 (class 1259 OID 33370)
-- Name: IX_OfferImages_OfferId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_OfferImages_OfferId" ON public."OfferImages" USING btree ("OfferId");


--
-- TOC entry 5894 (class 1259 OID 33371)
-- Name: IX_OfferReviews_CreatedById; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_OfferReviews_CreatedById" ON public."OfferReviews" USING btree ("CreatedById");


--
-- TOC entry 5895 (class 1259 OID 33372)
-- Name: IX_OfferReviews_OfferId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_OfferReviews_OfferId" ON public."OfferReviews" USING btree ("OfferId");


--
-- TOC entry 5879 (class 1259 OID 33373)
-- Name: IX_Offers_CategoryId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Offers_CategoryId" ON public."Offers" USING btree ("CategoryId");


--
-- TOC entry 5880 (class 1259 OID 33374)
-- Name: IX_Offers_CreatedById; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Offers_CreatedById" ON public."Offers" USING btree ("CreatedById");


--
-- TOC entry 5881 (class 1259 OID 33375)
-- Name: IX_Offers_PlaceId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Offers_PlaceId" ON public."Offers" USING btree ("PlaceId");


--
-- TOC entry 5884 (class 1259 OID 33376)
-- Name: IX_PlaceImages_PlaceId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_PlaceImages_PlaceId" ON public."PlaceImages" USING btree ("PlaceId");


--
-- TOC entry 5887 (class 1259 OID 33377)
-- Name: IX_PlaceLocations_LocationId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_PlaceLocations_LocationId" ON public."PlaceLocations" USING btree ("LocationId");


--
-- TOC entry 5888 (class 1259 OID 33378)
-- Name: IX_PlaceLocations_PlaceId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_PlaceLocations_PlaceId" ON public."PlaceLocations" USING btree ("PlaceId");


--
-- TOC entry 5876 (class 1259 OID 33379)
-- Name: IX_Places_CreatedById; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Places_CreatedById" ON public."Places" USING btree ("CreatedById");


--
-- TOC entry 5898 (class 1259 OID 33380)
-- Name: IX_UserSavedOffers_OfferId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_UserSavedOffers_OfferId" ON public."UserSavedOffers" USING btree ("OfferId");


--
-- TOC entry 5899 (class 1259 OID 33381)
-- Name: IX_UserSavedOffers_UserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_UserSavedOffers_UserId" ON public."UserSavedOffers" USING btree ("UserId");


--
-- TOC entry 5852 (class 1259 OID 33363)
-- Name: RoleNameIndex; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "RoleNameIndex" ON public."AspNetRoles" USING btree ("NormalizedName");


--
-- TOC entry 5856 (class 1259 OID 33368)
-- Name: UserNameIndex; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "UserNameIndex" ON public."AspNetUsers" USING btree ("NormalizedUserName");


--
-- TOC entry 5903 (class 2606 OID 33144)
-- Name: AspNetRoleClaims FK_AspNetRoleClaims_AspNetRoles_RoleId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetRoleClaims"
    ADD CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES public."AspNetRoles"("Id") ON DELETE CASCADE;


--
-- TOC entry 5904 (class 2606 OID 33159)
-- Name: AspNetUserClaims FK_AspNetUserClaims_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserClaims"
    ADD CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- TOC entry 5905 (class 2606 OID 33174)
-- Name: AspNetUserLogins FK_AspNetUserLogins_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserLogins"
    ADD CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- TOC entry 5906 (class 2606 OID 33186)
-- Name: AspNetUserRoles FK_AspNetUserRoles_AspNetRoles_RoleId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserRoles"
    ADD CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES public."AspNetRoles"("Id") ON DELETE CASCADE;


--
-- TOC entry 5907 (class 2606 OID 33191)
-- Name: AspNetUserRoles FK_AspNetUserRoles_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserRoles"
    ADD CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- TOC entry 5908 (class 2606 OID 33206)
-- Name: AspNetUserTokens FK_AspNetUserTokens_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserTokens"
    ADD CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- TOC entry 5902 (class 2606 OID 33129)
-- Name: OfferCategories FK_OfferCategories_OfferCategories_ParentId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."OfferCategories"
    ADD CONSTRAINT "FK_OfferCategories_OfferCategories_ParentId" FOREIGN KEY ("ParentId") REFERENCES public."OfferCategories"("Id");


--
-- TOC entry 5916 (class 2606 OID 33313)
-- Name: OfferImages FK_OfferImages_Offers_OfferId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."OfferImages"
    ADD CONSTRAINT "FK_OfferImages_Offers_OfferId" FOREIGN KEY ("OfferId") REFERENCES public."Offers"("Id") ON DELETE CASCADE;


--
-- TOC entry 5917 (class 2606 OID 33332)
-- Name: OfferReviews FK_OfferReviews_AspNetUsers_CreatedById; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."OfferReviews"
    ADD CONSTRAINT "FK_OfferReviews_AspNetUsers_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- TOC entry 5918 (class 2606 OID 33337)
-- Name: OfferReviews FK_OfferReviews_Offers_OfferId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."OfferReviews"
    ADD CONSTRAINT "FK_OfferReviews_Offers_OfferId" FOREIGN KEY ("OfferId") REFERENCES public."Offers"("Id") ON DELETE CASCADE;


--
-- TOC entry 5910 (class 2606 OID 33248)
-- Name: Offers FK_Offers_AspNetUsers_CreatedById; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Offers"
    ADD CONSTRAINT "FK_Offers_AspNetUsers_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES public."AspNetUsers"("Id");


--
-- TOC entry 5911 (class 2606 OID 33253)
-- Name: Offers FK_Offers_OfferCategories_CategoryId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Offers"
    ADD CONSTRAINT "FK_Offers_OfferCategories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES public."OfferCategories"("Id") ON DELETE CASCADE;


--
-- TOC entry 5912 (class 2606 OID 33258)
-- Name: Offers FK_Offers_Places_PlaceId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Offers"
    ADD CONSTRAINT "FK_Offers_Places_PlaceId" FOREIGN KEY ("PlaceId") REFERENCES public."Places"("Id") ON DELETE CASCADE;


--
-- TOC entry 5913 (class 2606 OID 33276)
-- Name: PlaceImages FK_PlaceImages_Places_PlaceId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PlaceImages"
    ADD CONSTRAINT "FK_PlaceImages_Places_PlaceId" FOREIGN KEY ("PlaceId") REFERENCES public."Places"("Id") ON DELETE CASCADE;


--
-- TOC entry 5914 (class 2606 OID 33291)
-- Name: PlaceLocations FK_PlaceLocations_Locations_LocationId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PlaceLocations"
    ADD CONSTRAINT "FK_PlaceLocations_Locations_LocationId" FOREIGN KEY ("LocationId") REFERENCES public."Locations"("Id") ON DELETE CASCADE;


--
-- TOC entry 5915 (class 2606 OID 33296)
-- Name: PlaceLocations FK_PlaceLocations_Places_PlaceId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PlaceLocations"
    ADD CONSTRAINT "FK_PlaceLocations_Places_PlaceId" FOREIGN KEY ("PlaceId") REFERENCES public."Places"("Id") ON DELETE CASCADE;


--
-- TOC entry 5909 (class 2606 OID 33226)
-- Name: Places FK_Places_AspNetUsers_CreatedById; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Places"
    ADD CONSTRAINT "FK_Places_AspNetUsers_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- TOC entry 5919 (class 2606 OID 33352)
-- Name: UserSavedOffers FK_UserSavedOffers_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."UserSavedOffers"
    ADD CONSTRAINT "FK_UserSavedOffers_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- TOC entry 5920 (class 2606 OID 33357)
-- Name: UserSavedOffers FK_UserSavedOffers_Offers_OfferId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."UserSavedOffers"
    ADD CONSTRAINT "FK_UserSavedOffers_Offers_OfferId" FOREIGN KEY ("OfferId") REFERENCES public."Offers"("Id") ON DELETE CASCADE;


-- Completed on 2026-05-26 12:34:01

--
-- PostgreSQL database dump complete
--


